name: Check

on:
  pull_request:
  push:

jobs:
  "Build":
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
    - name: Run command nix flake check
      run: nix flake check
